### ISSUE TITLE
error.code is undefined!!! 

### ISSUE THREAD

**Issue by bander-saeed94** [Level/level#116]

**Comment by ralphtheninja** [comment]
If you need help with something you really should give us a little more than that :smile:

**Comment by ralphtheninja** [comment]
So what error do you get?

**Comment by wookieb** [comment]
```javascript
if (error && error.code === 'NotFoundError')
```

**Comment by vweevers** [comment]
So the issue (or feature request) is that errors don't have a `code` property?

**Comment by vweevers** [comment]
Closing for lack of feedback; feel free to reopen.

**Comment by benfrancis** [comment]
Hi, I'm having a similar issue.

The documentation says:
> A not-found err object will be of type 'NotFoundError' so you can err.type == 'NotFoundError' or you can perform a truthy test on the property err.notFound.

When I `get()` a key that hasn't been `put()` (using the Promise interface) the error object returned has an `err.type` and `err.notFound` of `undefined`. If I print out the error response it returns the string "ReferenceError: privateKey is not defined". Is this the expected behaviour? What's a reliable way to check for a `NotFoundError`? Or does the ReferenceError mean something else and I'm doing something wrong?

Thanks

**Comment by vweevers** [comment]
> ReferenceError: privateKey is not defined

That's not coming from level. Try inspecting the stack trace (`err.stack` or just `console.error(err)` depending on runtime environment). Good luck!

**Comment by benfrancis** [comment]
@vweevers: Thanks, you're right. err.stack referenced a line of my own code that was causing the ReferenceError. When I deleted the database and started again the `NotFoundError` started working. Not sure what happened there.
