### ISSUE TITLE
build fails on io.js

### ISSUE THREAD

**Issue by ralphtheninja** [Level/level#16]
- [ ] update `leveldown` dependency to `~1.0.0`
- [ ] release new `level-packager` (https://github.com/Level/level-packager/issues/4) and update dependency

**Comment by timoxley** [comment]
https://github.com/iojs/io.js/issues/456

**Comment by jesstelford** [comment]
For anyone else who comes across this, the current workaround is to remove the `level` package from your dependencies, then install the `1.0.0-wip` branch of `levelup` along with the latest version of `leveldown`:

    npm install --save rvagg/node-levelup#1.0.0-wip leveldown

Then in your source, change instances of `var level = require('level')` to `var level = require('levelup')`

Once this issue is resolved, you should be able to remove the `levelup` and `leveldown` dependencies, and go back to using plain `level`.

**Comment by TEugen** [comment]
Could this be updated, please? We want to test io.js in our production stack, and we need the `level` module to work, otherwise our *management* department won't let us push for it

**Comment by mafintosh** [comment]
@TEugen I just released https://github.com/mafintosh/node-gyp-install which allows you to use level (and other deps that uses node-gyp) with io.js

**Comment by rvagg** [comment]
@mafintosh also [pangyp](https://github.com/rvagg/pangyp/) was my stopgap

**Comment by rvagg** [comment]
also, a 0.10.4 of leveldown was released a couple of days ago with some backports and io.js support, it's now the default (instead of 1.0.0) so "level" and others should just work with io.js and 0.12 now

**Comment by mafintosh** [comment]
@rvagg AWESOME. i had trouble getting it to work yesterday but it works now so probably just a bad cache or something. does that mean we can close this issue?

**Comment by rvagg** [comment]
prolly
