### ISSUE TITLE
Error while creating a web bundle with esbuild

### ISSUE THREAD

**Issue by ppedziwiatr** [Level/level#218]
Hey, I'm trying to use `level` in our project.

1. I've added the `level` as a dep in package.json
2. the esbuild configuration is here: https://github.com/redstone-finance/redstone-smartcontracts/blob/ppe/the-one-with-caching-per-transaction/bundle.js

During the build, esbuild throws 2 errors:
1. 
```
✘ [ERROR] Could not resolve "events"

    node_modules/abstract-level/abstract-level.js:5:33:
      5 │ const { EventEmitter } = require('events')
```
- it looks as if the "abstract"/common module is using node.js specific features - which obviously are not available in web env.

This can be "fixed" by adding `external: ['events']` in the `esbuild` configuration, but that's probably a workaround.

2. 
```
✘ [ERROR] Transforming async generator functions to the configured target environment ("chrome58", "es2020", "firefox57", "safari11") is not supported yet

    node_modules/abstract-level/abstract-iterator.js:320:2:
      320 │   async * [Symbol.asyncIterator] () {
```

in this case I haven't found a solution.

Has anyone used the `level` package with web bundlers?

**Comment by vweevers** [comment]
> This can be "fixed" by adding `external: ['events']` in the `esbuild` configuration, but that's probably a workaround.

That's the correct fix. As it stands, `level` is for Node.js first, browsers second. Bundlers should (be configured to) inject shims for Node.js core modules. Whether it's browserify (see [`browserify-starter`](https://github.com/Level/browserify-starter)), webpack (see [`webpack-starter/webpack.config.js`](https://github.com/Level/webpack-starter/blob/master/webpack.config.js)), esbuild or other.

> [ERROR] Transforming async generator functions to the configured target environment ("chrome58", "es2020", "firefox57", "safari11") is not supported yet

Safari < 12 is not supported by `level` because it doesn't support async generators (see [caniuse](https://caniuse.com/?search=async%20generator)).
