### ISSUE TITLE
Checking if a key exists

### ISSUE THREAD

**Issue by raineorshine** [Level/level#233]
I was surprised to find that `level` does not have a `has` function to check if a key exists in the database. `Map` has a `has` function. `localStorage.getItem` returns undefined. `level` throws a "Key not found error". 

Checking if a key exists is a common thing to do when initializing values in a key-value store.

Currently I put `db.get` in a try-catch, but that feels awkward. The solutions suggested in https://github.com/Level/level/issues/156#issuecomment-527757444 are counter-intuitive.

So out of curiosity, why not have a `db.has` function, or return `undefined` from `db.get`?

**Comment by vweevers** [comment]
See https://github.com/Level/community/issues/106 (and give it a thumbs up). PS. The referenced https://github.com/Level/level/issues/156#issuecomment-527757444 is for checking whether the db is empty, rather than checking whether a key exists.

As for `undefined`, see https://github.com/Level/abstract-level/pull/49 (will happen in `abstract-level` v2).
