### ISSUE TITLE
Random "LEVEL_DATABASE_NOT_OPEN" errors caused by "LEVEL_IO_ERROR"

### ISSUE THREAD

**Issue by lucassilvas1** [Level/level#245]
I have a little [NodeJS app](https://github.com/lucassilvas1/chromium-notification-retriever) that reads notification LevelDB databases of Chromium browsers. To do that, since it only needs read access, I copy the database to the project directory (`./db` to be specific), and use level to access it.
Since the purpose of the app is to watch for new notifications, I have [a function](https://github.com/lucassilvas1/chromium-notification-retriever/blob/474992897843f446125e61513cc866bff361288a/src/index.ts#L159) checking the directory of the original database for changes. When a change is found, the app closes the level instance, deletes the copy database, makes a new copy and creates a new instance of level.

Now the problem is: seemingly randomly I'll get the error below when I call the `open` method of level:

```
C:\Users\Lucas\Javascript\chromium-notifier\node_modules\chromium-notification-retriever\dist\index.js:163
                throw new Error("Something went wrong while opening database", {
                      ^

Error: Something went wrong while opening database
    at #refresh (C:\Users\Lucas\Javascript\chromium-notifier\node_modules\chromium-notification-retriever\dist\index.js:163:23)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Retriever.retrieve (C:\Users\Lucas\Javascript\chromium-notifier\node_modules\chromium-notification-retriever\dist\index.js:178:9)
    at async onChange (C:\Users\Lucas\Javascript\chromium-notifier\node_modules\chromium-notification-retriever\dist\index.js:221:35) {
  [cause]: ModuleError: Database is not open
      at maybeOpened (C:\Users\Lucas\Javascript\chromium-notifier\node_modules\abstract-level\abstract-level.js:133:18)
      at C:\Users\Lucas\Javascript\chromium-notifier\node_modules\abstract-level\abstract-level.js:160:13
      at process.processTicksAndRejections (node:internal/process/task_queues:77:11) {
    code: 'LEVEL_DATABASE_NOT_OPEN',
    cause: [Error: IO error: RenameFile C:\Users\Lucas\Javascript\chromium-notifier\node_modules\chromium-notification-retriever\dist\db\36d5ce362e72a17b690f6cac0b40b70f/000091.dbtmp C:\Users\Lucas\Javascript\chromium-notifier\node_modules\chromium-notification-retriever\dist\db\36d5ce362e72a17b690f6cac0b40b70f/CURRENT: Access is denied.
    ] {
      code: 'LEVEL_IO_ERROR'
    }
  }
}
```

That error is thrown at [this line](https://github.com/lucassilvas1/chromium-notification-retriever/blob/474992897843f446125e61513cc866bff361288a/src/index.ts#L191) here. 
It says it can't rename some temp file because access is denied. I'm not sure why that would be when I'm sure Node has write access to that folder, and if you look at that file I linked above, the only times the "copy database" directory is interacted with is when there's no level instance open. 
[This](https://github.com/lucassilvas1/chromium-notification-retriever/blob/474992897843f446125e61513cc866bff361288a/src/index.ts#L183) is the only function that ends up interacting with the "copy database" directory, and it does so only after explicitly closing the instance, so I don't see how the files could be busy while trying to open the instance either.

I've been experiencing this intermittently for weeks now, and I have no idea what could be causing it, especially because the code is so simple, I've looked at it dozens of times by now.

Thanks.

**Comment by vweevers** [comment]
We can't provide support for opening third-party databases; you might want to ask on StackOverflow.

But, I can tell you that Windows error codes like `ERROR_ACCESS_DENIED` shouldn't always be taken literally. This one also happens when the file has been deleted, or marked for deletion to be more precise. File deletion doesn't happen immediately; the file is put in a _delete-pending_ state. Subsequent attempts to open a file handle will then fail with `STATUS_DELETE_PENDING` which in user mode maps to `ERROR_ACCESS_DENIED`. See "File Deletion Semantics" in [File System Behavior in the Microsoft Windows Environment](https://go.microsoft.com/fwlink/?LinkId=140636) (an old document but still relevant on this particular point).

So you may want to try using a unique directory (and thus unique files) for each new copy. Or adding a retry, though that won't help if the deletion is delayed by some lingering open file handle.

Good luck!
