### ISSUE TITLE
Module version mismatch. Expected 46, got 48 on Node 4.1x

### ISSUE THREAD

**Issue by ralph-fuechtenkort** [Level/level#47]
Good Morning,

when i try to require esc/pos, i receive the error below.
fter some research i believe it has to do that the module is Node 6.1.x and i (have to) user 4.x as the app is a Meteor app.

**Is there a way to use the esc-pos module with node 4.x or is the error a different one.**

Thanks and Greets from Manila
Ralph

Exception while invoking method 'printEscPosTest' Error: Module version mismatch. Expected 46, got 48.
I20170607-12:58:08.300(8)?     at Error (native)
I20170607-12:58:08.300(8)?     at Object.Module._extensions..node (module.js:434:18)
I20170607-12:58:08.301(8)?     at Module.load (module.js:343:32)
I20170607-12:58:08.302(8)?     at Function.Module._load (module.js:300:12)
I20170607-12:58:08.303(8)?     at Module.require (module.js:353:17)
I20170607-12:58:08.303(8)?     at require (internal/module.js:12:17)
I20170607-12:58:08.304(8)?     at Object.<anonymous> (/projects/e-pos/epos-server/node_modules/usb/usb.js:5:38)
I20170607-12:58:08.305(8)?     at Module._compile (module.js:409:26)
I20170607-12:58:08.306(8)?     at Object.Module._extensions..js (module.js:416:10)

**Comment by ralphtheninja** [comment]
It would be nice if you could give some more information. This usually happens when you have installed node dependencies for one version of node (4.x in this case) and then update your version of node to something with an incompatible abi version (6.x).

I don't know what `esc/pos` and it doesn't seem to be any open source module I can help you with. Also, this happens when something is bundles for one version and later used by someone else with another environment, but is the same problem as trying to use binaries that are not compatible.

I suggest you wipe the `node_modules` folder for whatever application/module you are using and reinstall the dependencies with `npm install`.

**Comment by ralph-fuechtenkort** [comment]
Hi and good morning,
thanks for the reply. I am out of the office until saturday. I will try your approach to wipe and re-isnatll the node_modules folder of the module. I already looked in the package.json file there. It references node 6.1. Should i overwrite this with 4.1.x?
Greets from Manila
Ralph

**Comment by ralphtheninja** [comment]
> I already looked in the package.json file there. It references node 6.1. Should i overwrite this with 4.1.x?

Nah. Just re-installing dependencies should do it.
